### ISSUE TITLE
Only 5 leading good jets information saved in ntuples

### ISSUE THREAD

**Issue by ram1123** [atishelmanch/flashgg#12]
The p4 variables are saved for only first 5 leading jets. 

https://github.com/atishelmanch/flashgg/blob/683d7445ae341ec29aacd81e77bb7a82c513ae78/Systematics/python/HHWWggCustomize.py#L236-L241

Before this loop the variable `checkN` is set to 5. While for the b-discriminator variable it is set to 10.

https://github.com/atishelmanch/flashgg/blob/683d7445ae341ec29aacd81e77bb7a82c513ae78/Systematics/python/HHWWggCustomize.py#L264-L294

We should make the two numbers consistent.

**Comment by atishelmanch** [comment]
Let's close this issue after the PR [1] is merged 

[1] https://github.com/atishelmanch/flashgg/pull/16
