### ISSUE TITLE
Verify PDF Weight Computation and Saving

### ISSUE THREAD

**Issue by atishelmanch** [atishelmanch/flashgg#7]
Need to verify that PDF weights are properly computed and applied in the HH->WWgg analysis. Should be able to compute then with [recalculatePDFWeights](https://github.com/atishelmanch/flashgg/blob/HHWWgg_dev/Systematics/test/workspaceStd.py#L897) and dump them with [dumpPdfWeights](https://github.com/atishelmanch/flashgg/blob/HHWWgg_dev/Systematics/test/workspaceStd.py#L657). 

Assignee: @chuwang1

**Comment by chuwang1** [comment]
Thanks for your advice,I will test them in this weekend.

**Comment by atishelmanch** [comment]
Verified pdf weights saved in this release [1] 

[1] https://github.com/atishelmanch/flashgg/releases/tag/Jan2021Production
